[package]
name = "chat-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version="4.5.4", features=["derive"] }
tokio = { version="1.37.0", features=["rt", "macros", "signal", "io-std", "io-util", "net"] }
